---

# - hosts: db

#   gather_facts: yes

#   become: true

#   tasks:
#   - name: Add key for Mongodb
#     apt: pkg=mongodb state=present
#   - name: Cloning Git
#     git:
#       repo: https://github.com/shazid98/DevOps_eng114.git
#       dest: ~/
#       clone: yes
#       update: yes

#   - name: Replacing mongod.conf
#     shell:
#       cd /etc
#       rm mongod.conf
#       cp ~/DevOps_eng114/mongod.conf
#       sudo systemctl restart mongod
#       sudo systemctl enable mongod
#     become_user: root




- hosts: db

  gather_fact: yes

  become: true

  tasks:
  - name: Add key for Mongodb
    sudo: yes
    apt_key: >
      keyserver=hkp://keyserver.ubuntu.com:80
      id=D68FA50FEA312927
      state=present
  - name: Add mongo sources list
    sudo: yes
    lineinfile: > 
      line="deb https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse"
      dest=/etc/apt/sources.list.d/mongod.list
      state=present
      create=yes
  - name: Install mongo
    sudo: yes
    apt: name=mongodb-org state=latest update_cache=yes
