apiVersion: v1
kind: Service
metadata:
  name: node
  namespace: default
spec: 
  ports:
    - nodePort: 30000 # - 30000-302222
      port: 3000
      protocol: TCP
      targetPort: 3000

  selector:
    app: node
  type: NodePort