version: '3.7'

services:
  mongodb_container:
    image: shazid98/eng114-shazid-app:db1
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
  node_container:
    image: shazid98/eng114-shazid-app:v4
    ports:
      - 3000:3000
    depends_on:
      - mongodb_container
    environment:
      - DB_HOST=mongodb://mongodb_container:27017/posts

volumes:
  mongodb_data_container: 